/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eGUNGN9JdJI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { photo } from "@/images"
import Image from "next/image"

export default function Page() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-[#003366] text-white py-4 px-6 flex items-center justify-between">
        <Link href="#">
       <Image 
       src={photo}
       alt="some photo"
       />

        </Link>
        <nav className="flex items-center gap-6">
          <Link className="hover:underline" href="#">
            Login
          </Link>
          <Link className="hover:underline" href="/sign-up">
            Register
          </Link>
          <Link className="hover:underline" href="/">
            Dashboard
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="bg-[#f5f5f5] py-20">
          <div className="container mx-auto px-4 md:px-8">
            <div className="max-w-md mx-auto bg-white rounded-lg shadow-md p-8">
              <h2 className="text-2xl font-bold mb-4">Student Login</h2>
              <form>
                <div className="mb-4">
                  <label className="block text-gray-700 font-bold mb-2" htmlFor="name">
                    Name
                  </label>
                  <input
                    className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="name"
                    name="name"
                    placeholder="Enter your name"
                    required
                    type="text"
                  />
                </div>
                <div className="mb-4">
                  <label className="block text-gray-700 font-bold mb-2" htmlFor="email">
                    Email
                  </label>
                  <input
                    className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="email"
                    name="email"
                    placeholder="Enter your email"
                    required
                    type="email"
                  />
                </div>
                <div className="mb-4">
                  <label className="block text-gray-700 font-bold mb-2" htmlFor="student-id">
                    Student ID
                  </label>
                  <input
                    className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="student-id"
                    name="student-id"
                    placeholder="Enter your student ID"
                    required
                    type="text"
                  />
                </div>
                <div className="mb-6">
                  <label className="block text-gray-700 font-bold mb-2" htmlFor="password">
                    Password
                  </label>
                  <input
                    className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="password"
                    name="password"
                    placeholder="Enter your password"
                    required
                    type="password"
                  />
                </div>
                <div className="flex items-center justify-between">
                  <button
                    className="bg-[#003366] hover:bg-[#002a54] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                    type="submit"
                  >
                    Sign In
                  </button>
                  <a
                    className="inline-block align-baseline font-bold text-sm text-[#003366] hover:text-[#002a54]"
                    href="#"
                  >
                    Forgot Password?
                  </a>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#003366] text-white py-6 px-6 text-center">
        <p>© 2024 University of Ghana</p>
      </footer>
    </div>
  )
}
